server:
  port: 8081

spring:
  main:
#    web-application-type: none
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://localhost:27017/mybox
      username: root
      password: 1234
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

